### ISSUE TITLE
Обратная предобработка

### ISSUE THREAD

**Issue by Nikita94** [UNN-Data-Mining-Group/Data-Mining-Tool-System#102]
Нужны методы, с помощью которых можно из предобработанных выходных параметров, получить изначальные значения. 
Например выходной параметр ириса был преобразован к инту (1,2,3). При решении солвер выдал ответ 0.75 нужно преобразовать это параметр к изначальному стринговому значению.
@michael-smirnov поправь, пожалуйста, если мысль не правильно сфомировал.
Задача для  @ElenaM1234

**Comment by Nikita94** [comment]
@ElenaM1234  методы работают. Реализованы все преобразования? Если да, то issue можно закрывать

**Comment by ElenaM1234** [comment]
нет, еще не реализована бинаризация

**Comment by ElenaM1234** [comment]
Закрыть
