### ISSUE TITLE
Неправильно отбираются данные для обучения

### ISSUE THREAD

**Issue by ElenaM1234** [UNN-Data-Mining-Group/Data-Mining-Tool-System#103]
![image](https://cloud.githubusercontent.com/assets/23012420/23920764/fe490578-090c-11e7-81f6-17b5348d157c.png)
![image](https://cloud.githubusercontent.com/assets/23012420/23920789/1300e792-090d-11e7-8c39-0819ec985921.png)

Хотя выборка должна быть одна Выборка 963(для Ириса 2), а шаблоны: "New Template", "Iris2PreTemplate-Преобразование 376"

**Comment by ElenaM1234** [comment]
@Nikita94

**Comment by michael-smirnov** [comment]
@ElenaM1234 , PR, решающий эту проблему, замержен. Проверь, пожалуйста, и если проблема ушла - закрой задачу

**Comment by Nikita94** [comment]
@ElenaM1234

**Comment by ElenaM1234** [comment]
👍
