### ISSUE TITLE
Создание объекта DecisionTree из БД

### ISSUE THREAD

**Issue by Nikita94** [UNN-Data-Mining-Group/Data-Mining-Tool-System#111]
На данном этапе нельзя создать дерево решений из БД. 
Можно создать `TreeDescription topology = Solver.Description as TreeDescription;`
Но конструктор самих деревьев другой и он не может принять `TreeDescription`
Он принимает `public DecisionTree(long inputs, long outputs) : base(inputs, outputs)`

Задача для @Denzzel

**Comment by michael-smirnov** [comment]
@Nikita94 , а на каком этапе тебе нужно создавать объект `DecisionTree`?

**Comment by Denzzel** [comment]
@michael-smirnov мы с Никитой обсудили, я добавлю конструктор для того чтобы создавать дерево по описанию

**Comment by michael-smirnov** [comment]
@Denzzel , ок, понял

**Comment by michael-smirnov** [comment]
@Nikita94 , @Denzzel , задача еще не решена?

**Comment by Nikita94** [comment]
Да, деревья создаются из БД.
