### ISSUE TITLE
Ошибка обучения не отображается

### ISSUE THREAD

**Issue by michael-smirnov** [UNN-Data-Mining-Group/Data-Mining-Tool-System#145]
@Nikita94 , сейчас в проекте после обучения любого решателя все ошибки для него равны нулю, хотя после обучения и перед сохранением их в БД они нормальные.

**Comment by Nikita94** [comment]
@michael-smirnov  Вопрос не ко мне, так как ту часть давно никто не трогал. В мастере все окей отображается, возможно это из за манипуляций с БД. Лучше это Issue переадресовать @juraam

**Comment by juraam** [comment]
@michael-smirnov @Nikita94 манипуляции с бд с моей стороны не было.
Просто мы с Никитой наблюдали трабл что в деве нет таблицы одной в мастере есть и это вообще оч странно.

**Comment by juraam** [comment]
Короче я понял, что за ошибка в dev ветке.
Я просто сейчас попытался сохранить LearningQuality и он не сохранился.
Писал, что нет такого поля ClosingError.
Я глянул бд в дебаг папке и в корне дева там реально нет такого столбца. Посмотрев все бд, которые заливались в дев, понял, что вот коммит из пулла: https://github.com/UNN-Data-Mining-Group/Data-Mining-Tool-System/commit/8f340b20ad627f3a245bb86af7e2bcd591da103d
Потер данный столбец, и возможны ошибки при сохранении(у меня же он просто не сохранялся).
Также из бд данный коммит убрал TaskSLAnswer, про что у нас был разговор с @Nikita94 на выходных. Видимо Лена не подкачала все изменения и залила бд без моих изменений.
Они конечно потерлись и в деве сейчас ошибки есть.
В мастер этого Миша еще не заливал, поэтому ошибок там нет
Как убрать?
Ну @ElenaM1234 нужно взять бд из моего последнего коммита(нормального в деве) со всеми столбацми и таблицами, залить задачи, залить в реп, все остальные подхватят(благо решателей обученных еще нет нормальных), и перезапишут локальную бд.

**Comment by ElenaM1234** [comment]
поправлю вечером сегодня
