### ISSUE TITLE
Получение сущности БД по имени

### ISSUE THREAD

**Issue by michael-smirnov** [UNN-Data-Mining-Group/Data-Mining-Tool-System#35]
Во вьюмоделях часто возникает необходимость загрузить сущность БД - например `Task`, `TaskSolver`, `LearnedSolver`, `LearningScenario`. Есть возможность загрузить эти сущности из БД, используя бесполезный метод `getById` из `Entity` - во вьюмоделях мы не знаем id. 
Во вьюмоделях мы знаем содержательные характеристики сущностей, по которым можно их загрузить. 
Например, хотелось бы получить объект задачи по ее имени, загрузить `TaskSolver` по его имени и имени задачи, к которой он принадлежит.

**Comment by michael-smirnov** [comment]
@juraam, возможно добавить такие методы загрузки сущностей?

**Comment by juraam** [comment]
@michael-smirnov, это даже уже есть!) У любой сущности есть статический метод where, который берет объект Query и возвращает лист entity.
Как им пользоваться?
Очень похож на монговский запрос к бд.
Получить объект задачи по имени
Query query = new Query('Task').addTypeQuery(select).addCondition('name', '=', name);
List<Entity> tasks = Task.where(query);
и он вернет массив соответствующий запросу
Как строится запрос в конструкторе указывается имя таблицы. Потом обязательно нужно указать тип запроса(инсерт, селект, апдайт). И есть метод простенький addCondition. 1й параметр - имя колонки в таблице, операция и значение. Ну то есть в addCondition в sql запросах просто добавит строку nameColumn operation value. Вроде этого достаточно, чтобы в системе все добывать, и сложных запросов у нас думаю не предвидится.

**Comment by michael-smirnov** [comment]
@juraam, это все конечно хорошо, особенно после твоего объяснения. Однако мне нужно получать не массив сущностей, а одну, по аргументам, которые: 
1. ее однозначно определяют, как id
2. являются содержательными

Для этого городить огород из sql-подобных запросов мне кажется очень нелогичным. Считаю, что гораздо лучше в каждой сущности создать статический метод, возвращающий объект этой сущности по значениям данных аргументов. Например, в классе `Task` можно добавить метод `static Task load(string name)`. Или в `TaskSolver` метод `static TaskSolver load(string name, string taskName)`

**Comment by juraam** [comment]
Если мы в системе обязуем, что имя должно быть уникальным и повторений не будет, то окей.
Но внутри себя этот метод и будет использовать query.
А как часто нам нужно это использовать? И в каких местах нам нужно использовать?
Но метод создать не проблема.

**Comment by michael-smirnov** [comment]
Конечно, имя задачи должно быть уникально, иначе как их различать?
Для таск-солвера очевидно уникальна пара имя_задачи - имя_таск_солвера, и дальше по аналогии. 
Мне кажется ввести методы загрузки сущностей по таким параметрам нужно, т.к. любую сущность, которую нужно будет создавать и загружать в БД и которая имеет внутри себя ссылку на другую сущность в виде id, этот id нужно будет каким-то добывать.

Можно поступить другим образом: сейчас вью-моделям передается нужная им информация, но в виде строк. Например, вьюмодель,  занимающаяся созданием решателей, знает название задачи, для которой нужно создать решатель. Вместо имени можно передавать сам объект `Task`, после этого проблема отпадет сама собой. 

@juraam , как по твоему лучше?

**Comment by juraam** [comment]
@michael-smirnov методы по нейму ввести нет проблем.
Передавать объект хорошее решение, но вот у меня в голове крутится еще один способ: создать один глобальный объект, который будет хранить "местоположение" пользователя. Под местоположением подрузамеваю, taskId(если он открыл задачу), taskSolverId(если открыл таксолвер), selectionId(если открыл выборку). То есть вначале этот объект будет заполнен null. После открытия задачи, выборки, решателя в нем свойства его будут меняться. Но с этим и проблемы появятся с тем, чтобы зануливать не забывать все эти свойства.
Так что вариант передачи ссылок более приемлемый.

**Comment by michael-smirnov** [comment]
@juraam тут еще за глобальный объект говорит то, что при создании новых записей в БД нужно обновлять состояние некоторых вью-моделек (отображение дерева задач например). Можешь изменить вью-модельки? Создав глобальный объект или передавая объекты вместо строк?
