### ISSUE TITLE
Баг/фича Query.addCondition

### ISSUE THREAD

**Issue by michael-smirnov** [UNN-Data-Mining-Group/Data-Mining-Tool-System#39]
@juraam , При попытке использования addQuery, третий параметр приходится заключать в одинарные скобки: 

`Query q = new Query("Task").addTypeQuery(TypeQuery.select).addCondition("name", "=", "'" + taskName + "'");`

Нельзя ли автоматически создавать эти скобочки при формировании sql-запроса?

**Comment by juraam** [comment]
@michael-smirnov можно, я даже думал, что это уже так происходит, посмотрю.
Спасибо
