### ISSUE TITLE
Неправильная работа преобразований

### ISSUE THREAD

**Issue by michael-smirnov** [UNN-Data-Mining-Group/Data-Mining-Tool-System#75]
@ElenaM1234 , не понятно, как работают преобразования значений выборки. Например, бинаризация должна создавать новые параметры вместо преобразуемого.
Напиши пожалуйста сюда, как ты преобразуешь параметр каждого типа (int, real, enum) для каждого возможного преобразования (нормализация 1, 2 и бинаризация). После этого увидим, что нужно исправить.

**Comment by ElenaM1234** [comment]
![preprocessing](https://cloud.githubusercontent.com/assets/23012420/23707418/53334c2c-0423-11e7-9407-660150f5d810.jpg)

**Comment by michael-smirnov** [comment]
@ElenaM1234 ,
### Enum
- Норма 1 - согласен
- Норма 2 - не очевидно. Откуда взялся логарифм? Он по основанию 10? Между value и 2 не видно знака - плюс? умножить?
### Integer
- Норма 1 - в корне неверно. Что если при решении встретится значение, которого не было в обучающей выборке? К тому же данное преобразование не сохраняет отношения между значениями. Предлагаю сделать преобразование, которое переводит каждое значение `i:Integer` в нормализованное `ni:Float` по принципу `ni = ((Float)i - Min(i)) / (Max(i) - Min(i)) `, где максимум и минимум берутся по всем i из обучающей выборки.
- Норма 2 - тоже не очевидно. Надо объяснить, лучше на примере (после того, как будет исправлена норма 1) 
### Real
- Норма 1 - согласен.
- Норма 2 - нужно объяснить.
### Бинаризация
Так то оно так, но в системе этого пока нет, ты записываешь значения 1, 0, 0 в виде строчки в выходной атрибут: "(1,0,0)", а нужно удалить выходной атрибут и на его место добавить выходные атрибуты X1, X2 и X3.

**Comment by Destrouer** [comment]
@michael-smirnov ,
**Integer**

- Норма 1 - а если придёт инт больше\меньше чем в было в обучающей выборке? 👅

**Comment by michael-smirnov** [comment]
@Destrouer , я об этом тоже думал, но тут никак не исправить. Либо явно задавать min-max такими, что за их пределами значений быть не может в данной предметной области, либо неявно считать min-max значениями из выборки. Или у тебя есть идеи? :trollface:

**Comment by Destrouer** [comment]
@michael-smirnov , Вот и надо думать как такую ситуацию обходить, т.е. что мы будем делать если пользователь даст нам такие числа, или решатель вернёт такое значение

**Comment by michael-smirnov** [comment]
@Destrouer , мои предложения смотри выше, жду ваших. При обратном преобразовании от решателя, если значение выходит за рамки, можно просто ограничить минимумом/максимумом.

**Comment by michael-smirnov** [comment]
Еще, по бинаризации: нигде не говорили, поэтому считаю важным упомянуть, что бинаризованные значения представляют собой Int, а не Enum.

И еще, предлагаю сделать бинаризацию доступной только для параметров типа Enum. Иначе тоже возникнет проблема с конвертированием значений, не представленных в обучающей выборке.
