### ISSUE TITLE
Баг - отображение новых шаблонов

### ISSUE THREAD

**Issue by michael-smirnov** [UNN-Data-Mining-Group/Data-Mining-Tool-System#76]
При создании нового шаблона путем предобработки в окне "Информация о задаче" соответствующее преобразование появляется, а шаблон в комбобоксе нет. Надо исправить.
 Также, в окне "Информация о преобразовании" названия базового и порожденного шаблона отображаются некорректно. Плюс, у порожденного шаблона неправильные типы и количество входных и выходных параметров.

**Comment by ElenaM1234** [comment]
пофикшено в #78

**Comment by michael-smirnov** [comment]
Нет, не пофикшено - бинаризация не создает новых параметров. Выходных параметров порожденного шаблона должно быть несколько.

![default](https://cloud.githubusercontent.com/assets/5495597/23711103/50a11ae2-0438-11e7-92c2-861129dd6125.PNG)

**Comment by michael-smirnov** [comment]
@ElenaM1234 , ты шутишь что-ли? #96 не исправляет этой задачи

**Comment by michael-smirnov** [comment]
Сорри, смотрел другую ветку

**Comment by michael-smirnov** [comment]
@ElenaM1234 :+1:
