### ISSUE TITLE
Разобрать багу старта генетического алгоритма

### ISSUE THREAD

**Issue by Destrouer** [UNN-Data-Mining-Group/Data-Mining-Tool-System#82]
При запуске обучения - происходит падение, выглядит так, будто проблема в реализации алгоритма.
@michael-smirnov повесь это на меня, плиз.

**Comment by Destrouer** [comment]
Должно быть исправлено в #83 
Закрою после мёржа

**Comment by michael-smirnov** [comment]
@Destrouer , #83 смержил
